typer_assistant:
  assistant_name: Deeply
  human_companion_name: Luis
  ears: realtime-stt
  brain: deepseek-v3 # only deepseek-v3
  voice: elevenlabs # local, elevenlabs
  elevenlabs_voice: ErXwobaYiN019PkySvjV
base_assistant:
  assistant_name: Deeply
  human_companion_name: Luis
  ears: realtime-stt
  brain: deepseek-v3 # deepseek-v3, ollama:phi4, ollama:<any installed model>
  voice: elevenlabs # local, elevenlabs
  elevenlabs_voice: ErXwobaYiN019PkySvjV